### ISSUE TITLE
downloadable font: rejected by sanitizer

### ISSUE THREAD

**Issue by kghbln** [Hutchy68/pivot#16] opened 2017-03-18 20:18 UTC
## Setup
- MediaWiki 	1.27.1 (2f9cdcc) 17:23, 17 February 2017
- PHP 	5.6.30-0+deb8u1 (apache2handler)
- MariaDB 	10.0.30-MariaDB-1~jessie
- Pivot	1.0.0 (895feed) 21:55, 12 March 2017
- Firefox 52.0

## Issue
FontAwesome does not load and error console reveals:
```
downloadable font: rejected by sanitizer (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:1) source: https://pivot.wikiproject.net/w/skins/pivot/assets/fonts/fontawesome-webfont.woff2?af7ae  load.php:1:16254
```
## Related links
- https://github.com/FortAwesome/Font-Awesome/issues/8078
- http://stackoverflow.com/questions/11072655/firefox-font-face-fail-with-fontawesome

**Comment by Hutchy68** [comment] 2017-03-18 21:57
I can see Font Awesome is broken but I wonder if it is really this issue:

[Font-Awesome/issues/3286](https://github.com/FortAwesome/Font-Awesome/issues/3286)

I see invalid version tags in developer console for Chrome.

**Comment by kghbln** [comment] 2017-03-18 22:13
Yeah, and on Chrome it loads but obviously with random icons. :|

**Comment by Hutchy68** [comment] 2017-03-18 23:29
Is the server set up a duplicate of Foreground? I wonder if it is a MIME type error. There's no difference at all in the CSS between v4.3 and v4.7 in the way versions are called.

**Comment by Hutchy68** [comment] 2017-03-19 00:07
Ah ha... see the headers of the Pivot vs. Foreground and specifically, Content-Type.

Pivot site

```
Cache-Control:max-age=0
Content-Length:302
Content-Type:text/html; charset=iso-8859-1
Date:Sat, 18 Mar 2017 23:52:17 GMT
Expires:Sat, 18 Mar 2017 23:52:17 GMT
Location:https://pivot.wikiproject.net/
Server:Apache/2.4.10 (Debian)
```

vs.

Foreground
```
Accept-Ranges:bytes
Cache-Control:max-age=31536000
Connection:Keep-Alive
Content-Length:65452
Content-Type:application/font-woff
Date:Sat, 18 Mar 2017 23:12:23 GMT
Expires:Sun, 18 Mar 2018 23:12:23 GMT
Keep-Alive:timeout=5, max=97
Last-Modified:Fri, 01 Jul 2016 17:00:08 GMT
Server:Apache/2.4.10 (Debian)
```

It doesn't recognize the MIME type and is sending it as HTML not a font type.

**Comment by kghbln** [comment] 2017-03-19 19:21
> Ah ha... see the headers of the Pivot vs. Foreground and specifically, Content-Type.

I am absolutely puzzled as to why Apache is behaving differently. As a matter of fact I just copied the VirtualHost config file over and replaced foreground by pivot. I guess I am stuck in deep Apache irrationalities. We all love them :| Will try to figure out what is going on. Thanks for the pointer though.

**Comment by Hutchy68** [comment] 2017-03-19 21:22
Perhaps an .htaccess mime override somewhere in a foreground directory. 

https://github.com/fontello/fontello/wiki/How-to-setup-server-to-serve-fonts

Thing about .htaccess the override could be in /skins or /fonts of Foreground /assets for it to work without issue. 

I would try using the AddType first in .htaccess. If they start working then somewhere there's a config issue. If there's a proxy with nginx you might look there too.

**Comment by kghbln** [comment] 2017-03-20 16:19
> Perhaps an .htaccess mime override somewhere in a foreground directory.

Only if it comes with the code.

> https://github.com/fontello/fontello/wiki/How-to-setup-server-to-serve-fonts 

This was a live saver. I am back in business I believe. :)

This should probably be documented in the readme and on wiki?!

**Comment by Hutchy68** [comment] 2017-03-22 14:58
I created a page for Pivot [FAQs](https://pivot.wikiproject.net/wiki/FAQs) and will add the link to the README.md file. Closing this issue.

**Closed as completed by Hutchy68** 2017-03-22 14:58 UTC
Labels: Bug, CSS
